#!/usr/bin/env bash
# Generates .env with random MinIO credentials.
# Run from project root: ./scripts/init-env.sh

set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

USER="minio_$(openssl rand -hex 4)"
PASS="$(openssl rand -base64 24)"
REGION="${MINIO_REGION:-us-east-1}"

cat > "$ENV_FILE" << EOF
# Generated by scripts/init-env.sh — do not commit
MINIO_ROOT_USER=$USER
MINIO_ROOT_PASSWORD=$PASS
MINIO_REGION=$REGION

S3_ACCESS_KEY=$USER
S3_SECRET_KEY=$PASS
S3_REGION=$REGION
EOF

echo "Created $ENV_FILE"
echo "MINIO_ROOT_USER=$USER"
echo "MINIO_ROOT_PASSWORD=$PASS"
echo "S3_ACCESS_KEY=$USER"
echo "S3_SECRET_KEY=$PASS"
echo "MINIO_REGION=$REGION"
echo ""
echo "Restart MinIO: docker compose up -d minio"
